In [1]:
import pandas as pd
import numpy as np
from scipy import sparse

In [2]:
user_id = ['A','B','C','A','C','B']

item_name = ['prd1','prd2','prd3','prd4','prd5','prd6']

rating = [4,9,1,3,7,2]

In [3]:
sdf = pd.DataFrame({'user_id':user_id, 'item_name':item_name, 'rating':rating})

In [4]:
sdf

user_id item_name  rating
0       A      prd1       4
1       B      prd2       9
2       C      prd3       1
3       A      prd4       3
4       C      prd5       7
5       B      prd6       2

In [5]:
n_users = sdf['user_id'].unique()      #获得所有用户的id

n_items = sdf['item_name'].unique()    #获得所有产品的id

df = pd.DataFrame(index = n_users, columns = n_items) #生成一个基于用户为索引，产品为列的dataFrame  

In [8]:
for i in range(len(sdf)):
    row_i = sdf.iloc[[i]]
    user_id = row_i['user_id'].tolist()[0]
    item_name = row_i['item_name'].tolist()[0]
    rating = row_i['rating'].tolist()[0]
    df.at[user_id,item_name] = rating

In [9]:
df

prd1 prd2 prd3 prd4 prd5 prd6
A    4  NaN  NaN    3  NaN  NaN
B  NaN    9  NaN  NaN  NaN    2
C  NaN  NaN    1  NaN    7  NaN

In [10]:
df.fillna(0,inplace = True)

In [11]:
df

prd1  prd2  prd3  prd4  prd5  prd6
A     4     0     0     3     0     0
B     0     9     0     0     0     2
C     0     0     1     0     7     0

In [12]:
np.array(df)

array([[4, 0, 0, 3, 0, 0],
       [0, 9, 0, 0, 0, 2],
       [0, 0, 1, 0, 7, 0]], dtype=int64)

CSC是按列存储一个稀疏矩阵的。其中indptr中的数据代表矩阵中每一列所存的数据在data中的开始和结束的索引，  
而indices中的数据代表所对应的data中的数据在其所在列中的所在行数  

In [13]:
Csc = sparse.csc_matrix(np.array(df))

In [14]:
Csc.indptr

array([0, 1, 2, 3, 4, 5, 6], dtype=int32)

In [15]:
Csc.indices

array([0, 1, 2, 0, 2, 1], dtype=int32)

In [16]:
Csc.data

array([4, 9, 1, 3, 7, 2], dtype=int64)

CSR是按行来存储一个稀疏矩阵的，其原理与CSC类似。indptr中的数据表示矩阵中每一行的数据在data中开始和结束的索引，而indices中的数据表示所对应的在data中的数据在矩阵中其所在行的所在列数。可以看出，在indptr、indices和data三个数组相同的情况下，通过CSC和CSR分别表示出来的矩阵互为转置关系。

In [17]:
Csr = sparse.csr_matrix(np.array(df))

In [18]:
Csr.indptr

array([0, 2, 4, 6], dtype=int32)

In [19]:
Csr.indices

array([0, 3, 1, 5, 2, 4], dtype=int32)

In [20]:
Csr.data

array([4, 3, 9, 2, 1, 7], dtype=int64)

COO是最简单的一种格式，每一个元素需要用一个三元组来表示，分别是（行号，列号，数值）,但空间不是最优

In [21]:
Coo = sparse.coo_matrix(np.array(df))

In [22]:
Coo.row

array([0, 0, 1, 1, 2, 2], dtype=int32)

In [23]:
Coo.col

array([0, 3, 1, 5, 2, 4], dtype=int32)

In [24]:
Coo.data

array([4, 3, 9, 2, 1, 7], dtype=int64)

coo = csc.tocoo(copy=False)

In [25]:
pd.DataFrame({'index': Coo.row, 'col': Coo.col, 'data': Coo.data}
                 )[['index', 'col', 'data']].sort_values(['index', 'col']
                 ).reset_index(drop=True)

index  col  data
0      0    0     4
1      0    3     3
2      1    1     9
3      1    5     2
4      2    2     1
5      2    4     7

In [26]:
pd.DataFrame({'index': Coo.row, 'col': Coo.col, 'data': Coo.data}).sort_values(['index', 'col'])

index  col  data
0      0    0     4
1      0    3     3
2      1    1     9
3      1    5     2
4      2    2     1
5      2    4     7